[tool.poetry]
name = "vktest"
version = "0.1.0"
description = ""
authors = ["MarinaSlobozhaninova"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
